-- MySQL Script generated by MySQL Workbench
-- Wed Jul 19 16:36:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROLES` (
  `id_roles` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_roles`));


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `correo_usuario` VARCHAR(35) NOT NULL,
  `Contraseña` VARCHAR(32) NOT NULL,
  `puntos_pelicula_usuario` DECIMAL NOT NULL,
  `ROLES_id_roles` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_usuario`, `ROLES_id_roles`),
  INDEX `fk_USUARIO_ROLES1_idx` (`ROLES_id_roles` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_ROLES1`
    FOREIGN KEY (`ROLES_id_roles`)
    REFERENCES `mydb`.`ROLES` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIUDAD` (
  `ubicacion_ciudad` VARCHAR(16) NOT NULL,
  `nombre_ciudad` VARCHAR(255) NOT NULL,
  `direccion_ciudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ubicacion_ciudad`));


-- -----------------------------------------------------
-- Table `mydb`.`CARTELERA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CARTELERA` (
  `nombre_cartelera` VARCHAR(16) NOT NULL,
  `CIUDAD_ubicacion_ciudad` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`nombre_cartelera`, `CIUDAD_ubicacion_ciudad`),
  INDEX `fk_CARTELERA_CIUDAD1_idx` (`CIUDAD_ubicacion_ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_CARTELERA_CIUDAD1`
    FOREIGN KEY (`CIUDAD_ubicacion_ciudad`)
    REFERENCES `mydb`.`CIUDAD` (`ubicacion_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`PELICULA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PELICULA` (
  `nombre_pelicula` VARCHAR(50) NOT NULL,
  `productora_pelicula` VARCHAR(32) NOT NULL,
  `imagen_pelicula` VARCHAR(32) NOT NULL,
  `publico_dirigido_pelicula` VARCHAR(32) NOT NULL,
  `trailer_pelicula` VARCHAR(45) NOT NULL,
  `duracion_pelicula` VARCHAR(45) NOT NULL,
  `sinopsis_pelicula` VARCHAR(45) NOT NULL,
  `CARTELERA_nombre_cartelera` VARCHAR(16) NOT NULL,
  `CARTELERA_CIUDAD_ubicacion_ciudad` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`nombre_pelicula`, `CARTELERA_nombre_cartelera`, `CARTELERA_CIUDAD_ubicacion_ciudad`),
  INDEX `fk_PELICULA_CARTELERA1_idx` (`CARTELERA_nombre_cartelera` ASC, `CARTELERA_CIUDAD_ubicacion_ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_PELICULA_CARTELERA1`
    FOREIGN KEY (`CARTELERA_nombre_cartelera` , `CARTELERA_CIUDAD_ubicacion_ciudad`)
    REFERENCES `mydb`.`CARTELERA` (`nombre_cartelera` , `CIUDAD_ubicacion_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`SALA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SALA` (
  `num_sala` INT NOT NULL,
  `tipo_sala` VARCHAR(50) NOT NULL,
  `capacidad_sala` INT NOT NULL,
  `PELICULA_nombre_pelicula` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`num_sala`, `PELICULA_nombre_pelicula`),
  INDEX `fk_SALA_PELICULA1_idx` (`PELICULA_nombre_pelicula` ASC) VISIBLE,
  CONSTRAINT `fk_SALA_PELICULA1`
    FOREIGN KEY (`PELICULA_nombre_pelicula`)
    REFERENCES `mydb`.`PELICULA` (`nombre_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`ASIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASIENTO` (
  `numero_asiento` VARCHAR(16) NOT NULL,
  `SALA_num_sala` INT NOT NULL,
  PRIMARY KEY (`SALA_num_sala`),
  CONSTRAINT `fk_ASIENTO_SALA`
    FOREIGN KEY (`SALA_num_sala`)
    REFERENCES `mydb`.`SALA` (`num_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`RESERVACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RESERVACION` (
  `id_reservacion` DECIMAL NOT NULL,
  `fechas_disponibles_reservacion` DATE NOT NULL,
  `seleccion_idioma_reservacion` VARCHAR(32) NOT NULL,
  `seleccion_experiencia_reservacion` VARCHAR(32) NOT NULL,
  `metodo_pago_reservacion` VARCHAR(45) NOT NULL,
  `puntos_peliculas_reservacion` DECIMAL NOT NULL,
  `ASIENTO_SALA_num_sala` INT NOT NULL,
  PRIMARY KEY (`id_reservacion`, `ASIENTO_SALA_num_sala`),
  INDEX `fk_RESERVACION_ASIENTO1_idx` (`ASIENTO_SALA_num_sala` ASC) VISIBLE,
  CONSTRAINT `fk_RESERVACION_ASIENTO1`
    FOREIGN KEY (`ASIENTO_SALA_num_sala`)
    REFERENCES `mydb`.`ASIENTO` (`SALA_num_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`REPORTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REPORTES` (
  `id_reportes` DECIMAL NOT NULL,
  `descuentos_reportes` VARCHAR(50) NOT NULL,
  `peliculas_más_taquilleras_x_semana_reportes` VARCHAR(45) NOT NULL,
  `peliculas_más_taquilleras_x_mes_reportes` VARCHAR(45) NOT NULL,
  `ganancias_por_semanas_reportes` FLOAT NOT NULL,
  `ganancias_por_mes_reportes` FLOAT NOT NULL,
  `ROLES_id_roles` VARCHAR(16) NOT NULL,
  `RESERVACION_id_reservacion` DECIMAL NOT NULL,
  `RESERVACION_ASIENTO_SALA_num_sala` INT NOT NULL,
  PRIMARY KEY (`id_reportes`, `ROLES_id_roles`, `RESERVACION_id_reservacion`, `RESERVACION_ASIENTO_SALA_num_sala`),
  INDEX `fk_REPORTES_ROLES1_idx` (`ROLES_id_roles` ASC) VISIBLE,
  INDEX `fk_REPORTES_RESERVACION1_idx` (`RESERVACION_id_reservacion` ASC, `RESERVACION_ASIENTO_SALA_num_sala` ASC) VISIBLE,
  CONSTRAINT `fk_REPORTES_ROLES1`
    FOREIGN KEY (`ROLES_id_roles`)
    REFERENCES `mydb`.`ROLES` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REPORTES_RESERVACION1`
    FOREIGN KEY (`RESERVACION_id_reservacion` , `RESERVACION_ASIENTO_SALA_num_sala`)
    REFERENCES `mydb`.`RESERVACION` (`id_reservacion` , `ASIENTO_SALA_num_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`HORARIO` (
  `id_horario` INT NOT NULL,
  `inicio_horario` TIME NOT NULL,
  `fin_horario` TIME NOT NULL,
  `PELICULA_nombre_pelicula` VARCHAR(50) NOT NULL,
  `PELICULA_CARTELERA_nombre_cartelera` VARCHAR(16) NOT NULL,
  `PELICULA_CARTELERA_CIUDAD_ubicacion_ciudad` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_horario`, `PELICULA_nombre_pelicula`, `PELICULA_CARTELERA_nombre_cartelera`, `PELICULA_CARTELERA_CIUDAD_ubicacion_ciudad`),
  INDEX `fk_HORARIO_PELICULA1_idx` (`PELICULA_nombre_pelicula` ASC, `PELICULA_CARTELERA_nombre_cartelera` ASC, `PELICULA_CARTELERA_CIUDAD_ubicacion_ciudad` ASC) VISIBLE,
  CONSTRAINT `fk_HORARIO_PELICULA1`
    FOREIGN KEY (`PELICULA_nombre_pelicula` , `PELICULA_CARTELERA_nombre_cartelera` , `PELICULA_CARTELERA_CIUDAD_ubicacion_ciudad`)
    REFERENCES `mydb`.`PELICULA` (`nombre_pelicula` , `CARTELERA_nombre_cartelera` , `CARTELERA_CIUDAD_ubicacion_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FACTURA` (
  `num_factura` DECIMAL(50) NOT NULL,
  `fecha_factura` DATE NOT NULL,
  `nit_factura` VARCHAR(32) NOT NULL,
  `total_factura` FLOAT NOT NULL,
  `USUARIO_id_usuario` INT NOT NULL,
  `USUARIO_ROLES_id_roles` VARCHAR(16) NOT NULL,
  `RESERVACION_id_reservacion` DECIMAL NOT NULL,
  `RESERVACION_ASIENTO_SALA_num_sala` INT NOT NULL,
  PRIMARY KEY (`num_factura`, `USUARIO_id_usuario`, `USUARIO_ROLES_id_roles`, `RESERVACION_id_reservacion`, `RESERVACION_ASIENTO_SALA_num_sala`),
  INDEX `fk_FACTURA_USUARIO1_idx` (`USUARIO_id_usuario` ASC, `USUARIO_ROLES_id_roles` ASC) VISIBLE,
  INDEX `fk_FACTURA_RESERVACION1_idx` (`RESERVACION_id_reservacion` ASC, `RESERVACION_ASIENTO_SALA_num_sala` ASC) VISIBLE,
  CONSTRAINT `fk_FACTURA_USUARIO1`
    FOREIGN KEY (`USUARIO_id_usuario` , `USUARIO_ROLES_id_roles`)
    REFERENCES `mydb`.`USUARIO` (`id_usuario` , `ROLES_id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FACTURA_RESERVACION1`
    FOREIGN KEY (`RESERVACION_id_reservacion` , `RESERVACION_ASIENTO_SALA_num_sala`)
    REFERENCES `mydb`.`RESERVACION` (`id_reservacion` , `ASIENTO_SALA_num_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`DESCUENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DESCUENTO` (
  `id_descuento` INT NOT NULL,
  `valor_descuento` DOUBLE NOT NULL,
  `fecha_comienzo_descuento` DATE NOT NULL,
  `fecha_fin_descuento` DATE NOT NULL,
  `RESERVACION_id_reservacion` DECIMAL NOT NULL,
  `RESERVACION_ASIENTO_SALA_num_sala` INT NOT NULL,
  PRIMARY KEY (`id_descuento`, `RESERVACION_id_reservacion`, `RESERVACION_ASIENTO_SALA_num_sala`),
  INDEX `fk_DESCUENTO_RESERVACION1_idx` (`RESERVACION_id_reservacion` ASC, `RESERVACION_ASIENTO_SALA_num_sala` ASC) VISIBLE,
  CONSTRAINT `fk_DESCUENTO_RESERVACION1`
    FOREIGN KEY (`RESERVACION_id_reservacion` , `RESERVACION_ASIENTO_SALA_num_sala`)
    REFERENCES `mydb`.`RESERVACION` (`id_reservacion` , `ASIENTO_SALA_num_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
